baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Style Guide API'

themesDir = 'src/assets/hugo/themes'
publishDir = 'dist/docu'

[module]
[[module.mounts]]
  source = 'src/assets/hugo/archetypes'
  target = 'archetypes'
[[module.mounts]]
  source = 'src/docu'
  target = 'content'
[[module.mounts]]
  source = 'src/assets/hugo/data'
  target = 'data'
[[module.mounts]]
  source = 'src/assets/hugo/layouts'
  target = 'layouts'
[[module.mounts]]
  source = 'src/assets/hugo/static'
  target = 'static'


[markup]
  [markup.goldmark]
    [markup.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6